### ISSUE TITLE
Polygon lines wrapping around 0 degrees longitude

### ISSUE THREAD

**Issue by eranimo** [jdomingu/ThreeGeoJSON#10]
Thank you for writing this code, I'm using it to produce a sphere with Voronoi cells represented as GeoJSON polygon shapes. I am getting an interesting bug though:

<img width="570" alt="Screen Shot 2019-07-28 at 7 21 09 PM" src="https://user-images.githubusercontent.com/2599464/62014275-ef3f5400-b16c-11e9-8fdf-fc82e28353ac.png">

I believe that this is because of a bug in `interpolatePoints` when interpolating points on the "prime meridian" or 0 degrees longitude. It looks like it takes the longest path to the next point on the other side of that line, instead of the shortest path. I'm not sure exactly what's causing it.

**Comment by jdomingu** [comment]
Hey! Sorry for not replying. I haven't been on GitHub in a long time and have decided to archive the repository. I just haven't had the time or interest to dive into this project again, but I'm so glad that there were a few people that found it interesting!
