### ISSUE TITLE
'plane' not working with 'countries.json' provided

### ISSUE THREAD

**Issue by robksawyer** [jdomingu/ThreeGeoJSON#11]
I'm having some trouble getting the plane to render using the demo countries data. Any ideas?

Here's a demo https://codesandbox.io/s/react-three-fiber-geo-json-i0lmf?file=/src/App.js

**Comment by jdomingu** [comment]
Hey! Sorry for not replying. I haven't been on GitHub in a long time and have decided to archive the repository. I just haven't had the time or interest to dive into this project again, but I'm so glad that there were a few people that found it interesting!
