### ISSUE TITLE
Can I add color in each country? 

### ISSUE THREAD

**Issue by wubenhe** [jdomingu/ThreeGeoJSON#3]
I was wondering if it possible to add color into each country. Since you are drawing a line in 3d is it a way to draw shape in 3d as well?

**Comment by jdomingu** [comment]
Hmm...it wasn't intended to provide that kind of granularity, but if you wanted to make multiple calls to drawThreeGeo, that should work. E.g. you would have a separate geojson object for each country and set the color option with each call.

**Comment by wubenhe** [comment]
oh that mean I should bring the world json into each country's therefore I can draw the different color line. What about if I want to fill the color for the area instead of the line. (e.g.) US I want to fill the whole area to blue.

**Comment by jdomingu** [comment]
Closing out issues and archiving the repository. Sorry, this project was never meant to be more than a one-off, but I'm glad people found it interesting!
