### ISSUE TITLE
does the repo support polygon with hole?

### ISSUE THREAD

**Issue by dyh333** [jdomingu/ThreeGeoJSON#4]
hi, @jdomingu. I try to test polygon with hole using this repo, and change the rectangle data to this:
{
"type": "Feature",
"properties": {},
"geometry": {
"type": "Polygon",
"coordinates": [
  [
    [
      -131.1328125,
      -46.55886030311718
    ],
    [
      -131.1328125,
      55.97379820507658
    ],
    [
      66.4453125,
      55.97379820507658
    ],
    [
      66.4453125,
      -46.55886030311718
    ],
    [
      -131.1328125,
      -46.55886030311718
    ]
  ],
  [
    [
      -78.046875,
      -11.867350911459294
    ],
    [
      -78.046875,
      34.30714385628804
    ],
    [
      14.0625,
      34.30714385628804
    ],
    [
      14.0625,
      -11.867350911459294
    ],
    [
      -78.046875,
      -11.867350911459294
    ]
  ]
]
}
}

but not show the hode in three web, does the repo support polygon with hole? thanks

**Comment by jdomingu** [comment]
Hi @dyh333, this was mostly a pet project so all I'm doing to render polygons is draw their outlines as a line with threeJS. Sorry, there isn't a built-in way to hide polygon holes--the library will just render them as part of the polygon outline.

**Comment by dyh333** [comment]
thanks your reply. i got it.
