### ISSUE TITLE
Point Geometry not properly displayed

### ISSUE THREAD

**Issue by tempseptember** [jdomingu/ThreeGeoJSON#6]
> <html>
    <head>
        <title>ThreeGeoJSON Demo</title>
        <script src="lib/threeGeoJSON.js"></script>
        <script src="lib/three.js"></script>
        <script src="lib/TrackballControls.js"></script>
        <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    </head>
    <body>
        <style>
            html, body {
                padding: 0;
                margin: 0;
            }
        </style>
		<script type="text/JavaScript">
            var scene = new THREE.Scene();
            var camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.5, 1000);
            var renderer = new THREE.WebGLRenderer();
            renderer.setSize(window.innerWidth, window.innerHeight);
            document.body.appendChild(renderer.domElement);
            var planet = new THREE.Object3D();
            var geometry = new THREE.BoxGeometry(0,0,0);
            var material = new THREE.MeshBasicMaterial({
                color: 0x333333,
                wireframe: true,
                transparent: true
            });
            var sphere = new THREE.Mesh(geometry, material);
            planet.add(sphere);
            $.getJSON("test_geojson/bld_floor1base.geojson", function(data) {
                drawThreeGeo(data, 1, 'plane', {
                    color: 0x80FF80
                }, planet);
            });
            $.getJSON("test_geojson/bld_floor1rooms.geojson", function(data) {
                drawThreeGeo(data, 1, 'plane', {
                    color: 0x80FF80
                }, planet);
            });
            $.getJSON("test_geojson/bld_floor1ex.geojson", function(data) {
                drawThreeGeo(data, 0, 'sphere', {color: 0x80F080, size: 1}, planet);
            });
            scene.add(planet);
            camera.position.z = 15;
           var controls = new THREE.TrackballControls(camera);
           function render() {
                controls.update();
                requestAnimationFrame(render);
                renderer.render(scene, camera);
            }
            render();
        </script>
	</body>
</html>

This is the code.
The GeoJSON files can be obtained from the link
[https://github.com/tempseptember/threeproj](url)

**Comment by jdomingu** [comment]
Closing out issues and archiving the repository. Sorry, this project was never meant to be more than a one-off, but I'm glad people found it interesting!
