### ISSUE TITLE
Publish as NPM module

### ISSUE THREAD

**Issue by vasturiano** [jdomingu/ThreeGeoJSON#7]
Thanks for building this very useful module! Did you consider publishing [ThreeGeoJSON](https://github.com/jdomingu/ThreeGeoJSON/blob/master/lib/threeGeoJSON.js) as a reusable module on the public [NPM registry](https://www.npmjs.com/) so it can be easily integrated with other applications?

**Comment by AskAlice** [comment]
@jdomingu if you ever end up doing this, feel free to remove jquery via using something like
http://browserify.org/

**Comment by jdomingu** [comment]
Closing out issues and archiving the repository. Sorry, I never did get around to this!
